### ISSUE TITLE
AttributeError: 'CollectReport' object has no attribute 'description'

### ISSUE THREAD

**Issue by quanbanno2** [defnngj/pyautoTest#10]
+ python3 run_tests.py
回归模式，执行完成生成测试结果
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.6.3', 'Platform': 'Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core', 'Packages': {'pytest': '4.6.3', 'py': '1.8.0', 'pluggy': '0.12.0'}, 'Plugins': {'metadata': '1.8.0', 'html': '1.21.1', 'rerunfailures': '7.0'}, 'BUILD_NUMBER': '34', 'BUILD_ID': '34', 'BUILD_URL': 'http://192.168.0.196:8081/job/crm_auto_test/34/', 'NODE_NAME': 'master', 'JOB_NAME': 'crm_auto_test', 'BUILD_TAG': 'jenkins-crm_auto_test-34', 'EXECUTOR_NUMBER': '1', 'JENKINS_URL': 'http://192.168.0.196:8081/', 'JAVA_HOME': '/home/gaofenyun/app/jdk1.8.0_211', 'WORKSPACE': '/home/gaofenyun/.jenkins/workspace/crm_auto_test'}
plugins: metadata-1.8.0, html-1.21.1, rerunfailures-7.0
collecting ... collected 0 items / 1 errors
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 495, in perform_collect
INTERNALERROR>     items = self._perform_collect(args, genitems)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 534, in _perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 772, in genitems
INTERNALERROR>     for x in self.genitems(subnode):
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/_pytest/main.py", line 774, in genitems
INTERNALERROR>     node.ihook.pytest_collectreport(report=rep)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pytest_html/plugin.py", line 519, in pytest_collectreport
INTERNALERROR>     self.append_failed(report)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pytest_html/plugin.py", line 304, in append_failed
INTERNALERROR>     self._appendrow('Error', report)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pytest_html/plugin.py", line 273, in _appendrow
INTERNALERROR>     result = self.TestResult(outcome, report, self.logfile, self.config)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pytest_html/plugin.py", line 130, in __init__
INTERNALERROR>     report=report, cells=cells)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/gaofenyun/test_code/new_crm_poium/conftest.py", line 145, in pytest_html_results_table_row
INTERNALERROR>     cells.insert(2, html.td(report.description))
INTERNALERROR> AttributeError: 'CollectReport' object has no attribute 'description'

这种错误是什么引起的呢，这是我通过jenkins 使用selenium grid插件启动的，在我本地是可以正常运行。是什么原因呢？

**Comment by quanbanno2** [comment]
用例收集失败，原因是用例文件中存在服务器没有的模块。

**Comment by wanghaibo1996** [comment]
怎么定位到是哪个模块呢

**Comment by sijunji** [comment]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 621, in perform_collect
INTERNALERROR>     self.ihook.pytest_collectreport(report=rep)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 750, in pytest_collectreport
INTERNALERROR>     self.append_failed(report)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 465, in append_failed
INTERNALERROR>     self._appendrow("Error", report)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 433, in _appendrow
INTERNALERROR>     result = self.TestResult(outcome, report, self.logfile, self.config)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 199, in __init__
INTERNALERROR>     self.config.hook.pytest_html_results_table_row(report=report, cells=cells)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/python_data/TMT_QA_UI_Test/assess_new_m/conftest.py", line 65, in pytest_html_results_table_row
INTERNALERROR>     cells.insert(2, html.td(report.description))
INTERNALERROR> AttributeError: 'CollectReport' object has no attribute **'description'**
我在linux上运行selenium时，使用pytest-html插件初始化时遇到相同的问题，具体是什么原因啊

**Comment by wanghaibo1996** [comment]
你查看一下你的报告描述里是否有description



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "defnngj/pyautoTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [defnngj/pyautoTest] AttributeError: 'CollectReport' object has no attribute 'description' (#10)





 
INTERNALERROR&gt; Traceback (most recent call last):
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
 INTERNALERROR&gt;     session.exitstatus = doit(config, session) or 0
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
 INTERNALERROR&gt;     config.hook.pytest_collection(session=session)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in call
 INTERNALERROR&gt;     return self._hookexec(self, self.get_hookimpls(), kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
 INTERNALERROR&gt;     return self._inner_hookexec(hook, methods, kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in 
 INTERNALERROR&gt;     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
 INTERNALERROR&gt;     return outcome.get_result()
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
 INTERNALERROR&gt;     raise ex[1].with_traceback(ex[2])
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
 INTERNALERROR&gt;     res = hook_impl.function(*args)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 333, in pytest_collection
 INTERNALERROR&gt;     session.perform_collect()
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/_pytest/main.py", line 621, in perform_collect
 INTERNALERROR&gt;     self.ihook.pytest_collectreport(report=rep)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in call
 INTERNALERROR&gt;     return self._hookexec(self, self.get_hookimpls(), kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
 INTERNALERROR&gt;     return self._inner_hookexec(hook, methods, kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in 
 INTERNALERROR&gt;     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
 INTERNALERROR&gt;     return outcome.get_result()
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
 INTERNALERROR&gt;     raise ex[1].with_traceback(ex[2])
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
 INTERNALERROR&gt;     res = hook_impl.function(*args)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 750, in pytest_collectreport
 INTERNALERROR&gt;     self.append_failed(report)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 465, in append_failed
 INTERNALERROR&gt;     self._appendrow("Error", report)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 433, in _appendrow
 INTERNALERROR&gt;     result = self.TestResult(outcome, report, self.logfile, self.config)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pytest_html/plugin.py", line 199, in init
 INTERNALERROR&gt;     self.config.hook.pytest_html_results_table_row(report=report, cells=cells)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in call
 INTERNALERROR&gt;     return self._hookexec(self, self.get_hookimpls(), kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
 INTERNALERROR&gt;     return self._inner_hookexec(hook, methods, kwargs)
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/manager.py", line 87, in 
 INTERNALERROR&gt;     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
 INTERNALERROR&gt;     return outcome.get_result()
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
 INTERNALERROR&gt;     raise ex[1].with_traceback(ex[2])
 INTERNALERROR&gt;   File "/usr/local/python3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
 INTERNALERROR&gt;     res = hook_impl.function(*args)
 INTERNALERROR&gt;   File "/home/python_data/TMT_QA_UI_Test/assess_new_m/conftest.py", line 65, in pytest_html_results_table_row
 INTERNALERROR&gt;     cells.insert(2, html.td(report.description))
 INTERNALERROR&gt; AttributeError: 'CollectReport' object has no attribute 'description'
 我在linux上运行selenium时，使用pytest-html插件初始化时遇到相同的问题，具体是什么原因啊

**Comment by sijunji** [comment]
必然有啊，是不是pytest插件对linux不是很支持啊～

**Comment by wanghaibo1996** [comment]
这个我也不是很清楚，我用的是windows的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "defnngj/pyautoTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [defnngj/pyautoTest] AttributeError: 'CollectReport' object has no attribute 'description' (#10)





 
必然有啊，是不是pytest插件对linux不是很支持啊～

**Comment by sijunji** [comment]
我找到问题了，是因为存放测试用例的文件中的引用存在问题导致的
