### ISSUE TITLE
控制台输出

### ISSUE THREAD

**Issue by lonelyplant** [defnngj/pyautoTest#17]
你好，我尝试运行了一下 chrome headless 模式，控制台有部分乱码，想请教下这是什么东西的输出，怎么让它不乱码
![微信截图_20230413133606](https://user-images.githubusercontent.com/34595699/231663649-2253ee1d-36c2-4ca3-a8d2-59d96566aa3e.png)

**Comment by defnngj** [comment]
你可以尝试更新执行的用例，如果不再出现上面的乱花，那么很可能和执行的用例有关。

**Comment by lonelyplant** [comment]
我使用其他用例，再次执行后没有乱码。我打开原来的乱码中提到的源码，发现有一个 console.log 输出一些中文字符。于是我搜索后，发现是我终端的字体编码问题，执行命令 chcp 65001 后再执行原来的用例，正常输出中文了

![微信截图_20230508100734](https://user-images.githubusercontent.com/34595699/236718729-dce01856-5193-47ac-9697-515502fd63c4.png)
